// <auto-generated />
using CriminalDB.Database.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace CriminalDB.Migrations
{
    [DbContext(typeof(CriminalContext))]
    [Migration("20180505201318_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("CriminalDB.Database.Model.Crime", b =>
                {
                    b.Property<int>("CrimeID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("Time");

                    b.Property<string>("Type")
                        .IsRequired();

                    b.HasKey("CrimeID");

                    b.ToTable("Crimes");
                });

            modelBuilder.Entity("CriminalDB.Database.Model.CrimeCriminal", b =>
                {
                    b.Property<int>("CrimeID");

                    b.Property<int>("ID");

                    b.HasKey("CrimeID", "ID");

                    b.HasIndex("ID");

                    b.ToTable("CrimeCriminal");
                });

            modelBuilder.Entity("CriminalDB.Database.Model.CrimeVictim", b =>
                {
                    b.Property<int>("CrimeID");

                    b.Property<int>("ID");

                    b.HasKey("CrimeID", "ID");

                    b.HasIndex("ID");

                    b.ToTable("CrimeVictim");
                });

            modelBuilder.Entity("CriminalDB.Database.Model.Criminal", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("Description")
                        .HasMaxLength(250);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("Gender");

                    b.Property<double>("Height");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<double>("Weight");

                    b.HasKey("ID");

                    b.ToTable("Criminals");
                });

            modelBuilder.Entity("CriminalDB.Database.Model.Victim", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("Gender");

                    b.Property<double>("Height");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<double>("Weight");

                    b.HasKey("ID");

                    b.ToTable("Victims");
                });

            modelBuilder.Entity("CriminalDB.Database.Model.CrimeCriminal", b =>
                {
                    b.HasOne("CriminalDB.Database.Model.Crime", "Crime")
                        .WithMany("CrimeCriminals")
                        .HasForeignKey("CrimeID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CriminalDB.Database.Model.Criminal", "Criminal")
                        .WithMany("Crimes")
                        .HasForeignKey("ID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CriminalDB.Database.Model.CrimeVictim", b =>
                {
                    b.HasOne("CriminalDB.Database.Model.Crime", "Crime")
                        .WithMany("CrimeVictims")
                        .HasForeignKey("CrimeID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CriminalDB.Database.Model.Victim", "Victim")
                        .WithMany("Crimes")
                        .HasForeignKey("ID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
